name: CI testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  serialization-test:
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false # run all tests even if one fails
        matrix:
            python-version: [ "3.9", "3.10", "3.11"],
            input-file: [ "results_npz/millipede_wilks/run00136662.evt000035405932.neutrino_1.npz" ]

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Checkout test data from skymap_scanner
        uses: actions/checkout@v3
        with:
          repository: icecube/skymap_scanner
          ref: main
          path: skymap_scanner
          sparse-checkout: tests/data

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          pip install .

      - name: Run Python script
        # working-directory: auxiliary-repo/path/to/directory  # Replace 'path/to/directory' with the path to the directory containing your Python script
        run: python examples/npz_to_json.py --input-file skymap_scanner/tests/data/${{ matrix.input-file }} --output-dir .
